### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by spekulatius** [ninty9notout/silverstripe-colourpicker#4]
Hello @ninty9notout 

would you be able to tag a initial release for this module?

Cheers,
Peter

**Comment by ninty9notout** [comment]
Hey @spekulatius,

Sorry, I've not had much chance to maintain this one.

I've gone ahead and created a [1.0.0](https://github.com/ninty9notout/silverstripe-colourpicker/releases/tag/1.0.0) release for this.

I should have more time to keep an eye on this, so let me know if you have any issues.

Thanks,
H

**Comment by spekulatius** [comment]
Thank you :)
